import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import { config } from "@fortawesome/free-solid-svg-icons"
import "@fortawesome/fontawesome-svg-core/styles.css"
import Nav from "./(components)/Nav";


export const metadata = {
  title: "Ticket App",
  description: "Generated by Ravinder ",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen max-h-screen">
          <Nav />
          <div className="flex-grow overflow-auto bg-page text-default-text">
            {children}</div>
        </div>
      </body>

    </html >
  );
}
